//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAS.DataPorter.Monitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAS.DataPorter.Monitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some changes to the configuration may be available after restart of the application. It is suggested to restart the application now..
        /// </summary>
        internal static string ConfigurationForm_MessageAfterChange {
            get {
                return ResourceManager.GetString("ConfigurationForm_MessageAfterChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigurationFormName {
            get {
                return ResourceManager.GetString("ConfigurationFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_Open {
            get {
                object obj = ResourceManager.GetObject("Folder_Open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.commsvr.com/OPC-Help/Index.aspx?topic=html/b8c5f048-bb7e-4742-b7f2-b61a77789ed9.htm.
        /// </summary>
        internal static string OnlineDocumentation_url {
            get {
                return ResourceManager.GetString("OnlineDocumentation_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string tx_DataPorter_MainForm_buttonConnect {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_buttonConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string tx_DataPorter_MainForm_buttonDisconnect {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_buttonDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To generate a report, firstly connect to the DataPorter engine..
        /// </summary>
        internal static string tx_DataPorter_MainForm_connecttodoreport {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_connecttodoreport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem with license.
        /// (reason: &quot;{0}&quot;) 
        ///Verify or install new license.
        ///Click OK to close the application..
        /// </summary>
        internal static string tx_DataPorter_MainForm_LicenceExceptionOnInitialisation {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_LicenceExceptionOnInitialisation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----.
        /// </summary>
        internal static string tx_DataPorter_MainForm_noconnection {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_noconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        internal static string tx_DataPorter_MainForm_status_connected {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_status_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        internal static string tx_DataPorter_MainForm_status_disconnect {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_status_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to DataPorter engine: .
        /// </summary>
        internal static string tx_DataPorter_MainForm_unabletoconnect {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_unabletoconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from DataPorter engine:.
        /// </summary>
        internal static string tx_DataPorter_MainForm_warning_disconnected {
            get {
                return ResourceManager.GetString("tx_DataPorter_MainForm_warning_disconnected", resourceCulture);
            }
        }
    }
}
